<a href="https://colab.research.google.com/github/nabrajgharti8-tech/2407080_Nabaraj_Gharti_AI/blob/main/Worksheet_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np

#Problem 1

#1
a = np.zeros((2, 2))
print(a)

#2
brr = np.ones((4,2))
print(brr)

#3
crr = np.full((4,4),2)
print(crr)

#4
drr = np.zeros_like(a)
print(drr)

#5
err = np.ones_like(brr)
print(err)

#6
new_list = [1,2,3,4]
f = np.array(new_list)
print(f)


[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]
[[0. 0.]
 [0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
[1 2 3 4]


In [6]:
#Problem 2

#1
grr= np.arange(10,50)
print(grr)

#2
hrr= np.arange(0,9)

matrix = hrr.reshape(3,3)
print(matrix)

#3
irr = np.eye(3)
print(irr)

#4
jrr = np.random.random(30)
print(jrr)
mean = jrr.mean()
print(mean)

#5
krr = np.random.random((10,10))
print(krr)
print("Max Value", krr.max())
print("Min Value", krr.min())



[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0.10580616 0.58633568 0.12305892 0.19310386 0.14629645 0.08861728
 0.91930175 0.92131193 0.97606888 0.39119525 0.53310022 0.44641218
 0.45947431 0.23306044 0.43980674 0.26427801 0.26213561 0.97794559
 0.2410986  0.7507912  0.88731164 0.39959532 0.6735807  0.95813176
 0.07811512 0.70930943 0.48903758 0.56219194 0.21315014 0.15779792]
0.47291402068697025
[[0.36440356 0.5940657  0.59110855 0.88569453 0.11985794 0.67178078
  0.66109939 0.95152373 0.46564035 0.84380737]
 [0.08027886 0.4646118  0.48345549 0.39138933 0.41988094 0.04173031
  0.48274181 0.09720348 0.76596865 0.6551721 ]
 [0.73223401 0.89422002 0.46022153 0.78698417 0.18821338 0.57794639
  0.85518989 0.69985311 0.8297025  0.35675938]
 [0.00649025 0.01550151 0.58684681 0.26645168 0.36843665 0.04379834
  0.00342763 0.70556086 0.97909836 0.521570

In [7]:
#6
lrr = np.zeros(10)
print(lrr)
lrr[4] = 1
print(lrr)

#7
arr = [1,2,0,0,4,0]
arr_np = np.array(arr)
print(arr_np)
reversed = np.flip(arr_np)
print(reversed)

#8
mrr = np.zeros((5,5), dtype=int)
mrr[0, :]= 1 #top row
mrr[-1, :]= 1 #bottom row
mrr[:, 0]= 1  #left column
mrr[:, -1]= 1 #right column
print(mrr)

#9
nrr= np.zeros((8,8), dtype=int)
nrr[1::2, ::2] = 1 #row: 1,3,5,7 column: 0,2,4,6
nrr[::2, 1::2] = 1#row 0,2,4,6 column: 1,3,5,7
print(nrr)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[1 2 0 0 4 0]
[0 4 0 0 2 1]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [8]:
#Problem 3
x = np.array([[1,2],[3,5]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11,12]);

add_1= x + y
add_2 = v + w
print(add_1)
print(add_2)

sub_1 = x - y
sub_2 = v - w
print(sub_1)
print(sub_2)

multiplication = x * 2
multiplication_1 = w * 9
print(multiplication)
print(multiplication_1)

x_square = x ** 2
print(x_square)
y_square = y ** 2
print(y_square)
v_square = v ** 2
print(v_square)
w_square = w ** 2
print(w_square)

V_W = np.dot(v, w)
print("Dot Product between v and w",V_W)

X_Y = np.dot(x, y)
print("Dot Product between x and y \n", X_Y)

row_concat = np.concatenate((x,y), axis=0)
print(row_concat)

column_concat = np.vstack((v,w))
print(column_concat)

# concat_xv = np.concatenate((x,v), axis=0)
# print(concat_xv)
#all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

[[ 6  8]
 [10 13]]
[20 22]
[[-4 -4]
 [-4 -3]]
[-2 -2]
[[ 2  4]
 [ 6 10]]
[ 99 108]
[[ 1  4]
 [ 9 25]]
[[25 36]
 [49 64]]
[ 81 100]
[121 144]
Dot Product between v and w 219
Dot Product between x and y 
 [[19 22]
 [50 58]]
[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [9]:
#Problem 4

#1
A = np.array([[3,4],[7,8]])
B = np.array([[5,3],[2,1]])

I = np.eye(2, dtype=int)

A_inv = np.linalg.inv(A)
AdotA_inv = np.dot(A, A_inv)

AdotA_inv_int = np.round(AdotA_inv).astype(int)
print(AdotA_inv_int)

if np.array_equal(AdotA_inv_int, I):
    print("True")
else:
    print(False)

#2
AdotB = np.dot(A,B)
BdotA = np.dot(B,A)

print(AdotB)
print(BdotA)

if np.array_equal(AdotB, BdotA):
    print("Equal")
else:
    print("Not Equal")


#3
AdotB = np.dot(A,B)
AdotB_T = AdotB.T

B_T = B.T
A_T = A.T
B_TdotA_T = np.dot(B_T, A_T)

if np.array_equal(AdotB_T, B_TdotA_T):
    print("Equal: (AB)^T = B^T A^T")
else:
    print("NotEqual")



[[1 0]
 [0 1]]
True
[[23 13]
 [51 29]]
[[36 44]
 [13 16]]
Not Equal
Equal: (AB)^T = B^T A^T


In [10]:
#Linear Equations
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]])
B = np.array([[-1],[-3],[9]])

Ainv = np.linalg.inv(A)
x = np.dot(Ainv, B)

print(x)

[[ 2.]
 [ 1.]
 [-2.]]


In [11]:
#Element-Wise Addition

import time
import numpy as np

n = 1_00_000

list1 = list(range(n))
list2 = list(range(n))

start_time = time.time()
list_sum = [list1[i] + list2[i] for i in range(n)]
end_time = time.time()
print("Time taken for Python list addition:", end_time - start_time, "seconds")

arr1 = np.array(n)
arr2 = np.array(n)

start_time = time.time()
arr_sum = arr1 + arr2
end_time = time.time()
print("Time taken for NumPy array addition:", end_time - start_time, "seconds")


Time taken for Python list addition: 0.012070894241333008 seconds
Time taken for NumPy array addition: 0.00010514259338378906 seconds


In [12]:
#Element wise Multiplication

import time
import numpy as np

n = 1_00_000

list1 = list(range(n))
list2 = list(range(n))

start_time = time.time()
list_product = [list1[i] * list2[i] for i in range(n)]
end_time = time.time()
print("Time taken for Python list multiplication:", end_time - start_time, "seconds")

arr1 = np.arange(n)
arr2 = np.arange(n)

start_time = time.time()
arr_product = arr1 * arr2
end_time = time.time()
print("Time taken for NumPy array multiplication:", end_time - start_time, "seconds")


Time taken for Python list multiplication: 0.013091802597045898 seconds
Time taken for NumPy array multiplication: 0.0007321834564208984 seconds


In [13]:
#Dot Product

import time
import numpy as np

n = 1_00_000

list1 = list(range(n))
list2 = list(range(n))

start_time = time.time()
dot_list = sum(list1[i] * list2[i] for i in range(n))
end_time = time.time()
print("Time taken for Python list dot product:", end_time - start_time, "seconds")

arr1 = np.arange(n)
arr2 = np.arange(n)

start_time = time.time()
dot_arr = np.dot(arr1, arr2)
end_time = time.time()
print("Time taken for NumPy array dot product:", end_time - start_time, "seconds")


Time taken for Python list dot product: 0.011471271514892578 seconds
Time taken for NumPy array dot product: 0.0005257129669189453 seconds


In [4]:
import time
import numpy as np
import random

n = 1000

matrix1 = [[random.randint(0,10) for i in range(n)] for i in range(n)]
matrix2 = [[random.randint(0,10) for i in range(n)] for i in range(n)]

start_time = time.time()

result_list = [[0]*n for i in range(n)]

for i in range(n):
    for j in range(n):
        for k in range(n):
            result_list[i][j] += matrix1[i][k] + matrix2[k][j]

end_time = time.time()
print("Time taken for Python list Matrix Multiplication", end_time - start_time , "seconds")

arr1 = np.random.randint(0, 10, size=(n,n))
arr2 = np.random.randint(0, 10, size=(n,n))

start_time = time.time()
result_np = np.dot(arr1, arr2)
end_time = time.time()
print("Time taken for Numpy Array Matrix Multiplication", end_time - start_time , "seconds")


Time taken for Python list Matrix Multiplication 281.48981070518494 seconds
Time taken for Numpy Array Matrix Multiplication 2.123913288116455 seconds
